name: Django CI with Firebase

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    # Instala dependências da raiz
    - name: Install root dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Instala dependências específicas do backend
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        pip install firebase-admin
        
    - name: Set up Firebase credentials
      working-directory: ./backend
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json
        
    - name: Run tests
      working-directory: ./backend
      env:
        GOOGLE_APPLICATION_CREDENTIALS: firebase_credentials.json
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        python manage.py test
